[secret]
env_path = "/etc/domotik/automations.env"
env_names = ["MAIL_FROM", "MAIL_TO", "SMTP_USERNAME", "SMTP_PASSWORD"]

[database]
path = "/home/domotik/database/domotik.db"

[mqtt]
hostname = "localhost"
port = 1883

[domio]
hostname = "localhost"
port = 8100

[smtp]
hostname = "smtp.gmail.com"
port = 587

[linky]
apparent_power_alert = 250
check_time = "23:30"

[logger]
aiohttp = "WARNING"
aiosqlite = "WARNING"

[logger.automations]
tasks = "INFO"
db = "INFO"

[periodicity]
outdoor = 300
pressure = 600
linky = 60
